name: "Build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build-backend:
    name: "API, Functions"
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.x"
        dotnet-quality: "ga"

  build-website:
    name: "Website"
    runs-on: ubuntu-latest
      
    steps:
      
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: 'npm'
  
    - name: Install packages
      run: npm install
  
    - name: Build site
      run: npm run build.prod
